spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:~/Documents/utility/testdb

  jpa:
    database: h2
    defer-datasource-initialization: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true



